$('.footerLinks').click(function() {
    let modalTitle, modalContent
    console.log($(this).attr('id'))
    switch($(this).attr('id')){
        case "terms":
            modalTitle = "Terms &amp; Conditions"
            modalContent = `
                <p><span>PLEASE CAREFULLY READ THESE TERMS AND CONDITIONS (COLLECTIVELY WITH ANY AMENDMENTS), “TERMS AND CONDITIONS”) BEFORE PLACING AN ORDER OR USING THIS WEBSITE. THIS WEBSITE IS OWNED AND OPERATED BY SERA LABS, INC.® AND ITS AFFILIATES (COLLECTIVELY “SERA LABS, INC.®“, “US”, “THE”, “WE” or “OUR”). THE TERMS AND CONDITIONS MAY AFFECT YOUR LEGAL RIGHTS, INCLUDING YOUR RIGHT TO BRING A LAWSUIT OR CLASS ACTION.</span></p><br>
                <p><span>BY USING THIS WEB SITE OR ANY WEB SITE OF SERA LABS INC.® AND/OR PLACING AN ORDER FOR SERA LABS, INC® PRODUCTS OR SERVICES, YOU AGREE TO BE BOUND AND ABIDE BY THESE TERMS AND CONDITIONS AND ANY AMENDMENTS THERETO, AND AGREE THAT YOU ARE AT LEAST 18 YEARS OF AGE AND ELIGIBLE TO USE THIS SITE AND PLACE AN ORDER FOR SERA LABS, INC.® PRODUCTS AND SERVICES.</span></p><br>
                <p><span>IF YOU ARE NOT 18 YEARS OF AGE, YOU MUST USE THIS SITE AND/OR PURCHASE AND USE SERA LABS, INC.® PRODUCTS OR SERVICES ONLY WITH THE INVOLVEMENT OF YOUR PARENT OR GUARDIAN.</span></p><br>
                <p><span>IF YOU DO NOT AGREE TO THE TERMS AND CONDITIONS, PLEASE DO NOT USE THE SITE OR ORDER OR USE SERA LABS, INC.® PRODUCTS OR SERVICES.</span></p><br>
                <p><span>We may update or amend these Terms and Conditions from time to time to comply with law or to meet our changing business requirements without notice to you. Your continued use of the Sites and/or other products or services of Sera Labs, Inc.® after any such changes constitutes your acceptance of the new Terms and Conditions. Any updates or amendments will be posted on the Sites. The Terms and Conditions displayed on the Sites at the time the order is accepted will apply to the order. These Terms and Conditions govern and apply to your (“you” or “your”) access to and use of the Sites and their related domains on which these Terms and Conditions appear, any order you place through any of the Sites, and to all products and services we supply, produce, distribute, or market. To the extent of any express inconsistency with any other agreement you may have with Sera Labs, Inc.® for products, services, or otherwise, that other agreement shall prevail unless otherwise explicitly stated therein. If these Terms and Conditions refer or relate to a clause that is not part of that other agreement, then these terms shall apply therein as well, if you are a user of the Sites. If you register for our Support Center features, additional rules, policies, and disclaimers may apply.</span></p><br>
                <p><span>Unused/Unopened products may be returned at the customer’s expense, we do not offer return vouchers, with an RMA number issued at customer care&nbsp;<a href="https://help.seralabshealth.com/">help.seralabshealth.com, or 1-800-625-4211.&nbsp;</a>Refunds will be issued only after the fulfillment center has thoroughly inspected the return. No refunds will be issued on damaged product, or product with broken seals, or product not returned. All unopened/seal not broken returns are subject to the 30 Day Money Back Guarantee (from date of purchase), any product returned after the 30-Day Money Back Guarantee will not receive a refund. We can not legally accept product returns that have been opened/seal broken, products in this condition can not be refunded.&nbsp; All returns will be subject to restocking fee (see Shipping/Returns-Contact Us). All promotional product discount offers that were given free shipping at the time of purchase, that cancel/return, are considered early termination and may be subject to shipping charge at time of cancel or product return. Please refer to the Return Policy for complete information. We do not offer rush shipping, only front of line processing. All returns where only shipping was charged will not be refunded, as shipping is not a refundable charge.&nbsp;</span></p><br>
                <p><span>*Prices/Packages are subject to change at any time without notice.</span></p><br>
                <p><span>Sera Labs, Inc. is not responsible for delays in shipping, due to inclement weather, holidays, or world disaster. Please refer to Shipping Policy for complete information. Please be advised that during Covid-19 all carriers are experiencing longer shipping times, and delays.</span></p><br>
                <p><strong>VIP Replenish Program</strong></p><br>
                <p><span>The Free VIP Replenishment Program means that in approximately, depending on the package size purchased, 30/60/90/120/150/180 days from your initial order and subsequently thereafter, you will be shipped a fresh new supply of product/products purchased at the low guarantee VIP price. Prior to being billed for your replenishment order you will receive notification sent to the email address you provided with your purchase. You can cancel your VIP Replenishment Program at any time by contacting our Customer Care Department at&nbsp;<a href="https://help.seralabshealth.com/">help.seralabshealth.com</a>&nbsp;or send an email to&nbsp;<a href="https://help.seralabshealth.com/">help.seralabshealth.com or call 1-800-625-4211.&nbsp;</a></span><span>In addition to free enrollment in the VIP Replenishment Program, you will also be subscribed to our Sera Labs Health mailing list to receive occasional emails regarding new products, and new promotions. If you do not wish to receive any promotional emails please contact customer care.</span></p><br>
                <p><strong>User Conduct</strong></p><br>
                <p><span>You must only use the Sites for lawful purposes, and you must not use them in a way that infringes the rights of anyone else or that restricts or inhibits anyone else’s enjoyment of the Sites. You may not without our prior written consent:</span></p><br>
                <p><span>copy, reproduce, use, or otherwise deal with any content on the Sites;</span></p><br>
                <p><span>modify, distribute, or re-post any content on the Sites for any purpose; or</span></p><br>
                <p><span>use the content of the Sites for any commercial exploitation whatsoever.</span></p><br>
                <p><span>In using the Sites, you further agree:</span></p><br>
                <p><span>not to disrupt or interfere with the security of, or otherwise abuse, the Sites, or any services, system resources, accounts, servers, or networks connected to or accessible through the Sites or affiliated or linked sites;</span></p><br>
                <p><span>not to disrupt or interfere with any other user’s enjoyment of the Sites or affiliated or linked Websites;</span></p><br>
                <p><span>not to upload, post, or otherwise transmit through or on the Sites any viruses or other harmful, disruptive, or destructive files;</span></p><br>
                <p><span>not to use, frame, or utilize framing techniques to enclose any Sera Labs, Inc.® trademark, logo, or other proprietary information (including the images found at the Sites, the content of any text, or the layout/design of any page or form contained on a page) without Sera Labs, Inc.® express written consent; not to use meta tags or any other “hidden text” utilizing a Sera Labs, Inc.® name, trademark, or product name without Sera Labs, Inc.® express written consent; not to deep link to this Sites without Sera Labs, Inc.® express written consent; not to create or use a false identity on the Sites, share your account information, or allow any person besides yourself to use your account to access the Sites; not to collect or store personal data about others;</span></p><br>
                <p><span>not to attempt to obtain unauthorized access to the Sites or portions of the Sites that are restricted from general access; not to post any material that is knowingly false and/or defamatory, inaccurate, abusive, vulgar, hateful, harassing, obscene, profane, sexually oriented, threatening, invasive of a person’s privacy, or otherwise violating of any law. You also agree not to post any copyrighted material unless the copyright is owned by you or by Sera Labs, Inc.®; and to be bound by the Product Submission Policies of Sera Labs, Inc.®, including that any product submission you may make to Sera Labs, Inc.® will not be held in confidence by Sera Labs, Inc.®, and is not proprietary, that Sera Labs, Inc.® may use the product submission and any aspect thereof for any purposes in Sera Labs, Inc.® sole discretion, and that Sera Labs, Inc.® owes no duties or obligations with respect to you or the product submission made. In addition, you agree that you will comply with all applicable local, national, and international laws and regulations that relate to your use of or activities on the Sites. We will not be responsible, or liable to any third party, for the content or accuracy of any materials posted by you or any other user of the Sites. We have the right to remove any material or posting you make on the Sites if, in our opinion, such material does not comply with the content standards set out in these Terms and Conditions. The views and opinions of authors, trainers, experts and any other contributors expressed herein do not necessarily state or reflect the attitudes and opinions of Sera Labs, Inc.®. These views and opinions shall not be attributed to or otherwise endorsed by Sera Labs, Inc.®, and may not be used for advertising or product endorsement purposes without the express, written consent of Sera Labs, Inc.®.</span></p><br>
                <p><strong>Privacy Policy</strong></p><br>
                <p><span>Users of the Sites and/or other products or services of Sera Labs, Inc.® should refer to Sera Labs, Inc.® Privacy Policy for information about how Sera Labs, Inc.® uses and collects information, which may be accessed by clicking on the appropriate link on the particular Site that you visited. You agree that Sera Labs, Inc.® may disclose your personal information to a third party if Sera Labs, Inc.® believes in good faith that the law or legal process requires it, to protect the rights or property of Sera Labs, Inc.® or others, or as otherwise described in the Privacy Policy. Content Uploaded to the Sites</span></p><br>
                <p><span>In the event that you upload any photographs, comments, video clips, or other media to the Sites (the “Uploaded Content”), Sera Labs, Inc.® has the exclusive right to use any and all such elements of the Uploaded Content in connection with and/or as part of its business, including in connection with and/or in any advertising in any and all media, including, without limitation, product packaging, printed publications, presentations, promotional materials, events and associated marketing materials, television and cinema commercials, videos, or Web sites, in perpetuity throughout the world as Sera Labs, Inc.® in its sole discretion sees fit without further consent or payment. Sera Labs, Inc.® has all right, title, and interest in any and all results and proceeds from such use of the Uploaded Content. Sera Labs, Inc.® has the right to transfer the aforementioned rights to use the Uploaded Content to any third party, including, but not limited to, any of its subsidiaries or affiliated companies. Sera Labs, Inc.® may alter, adapt, or edit the Uploaded Content and any further material created under these Terms and Conditions, and market and exploit it entirely at Sera Labs, Inc.® sole discretion. Sera Labs, Inc.® is not obliged to make any use of the Uploaded Content or exercise any of the rights granted by these Terms and Conditions.</span></p><br>
                <p><span>Users of the Sites must only post Uploaded Content that is owned by, and features, themselves, and no other third parties. Users posting Uploaded Content via a user profile must treat their login credentials and password confidential and ensure that they are not shared with any third party that might jeopardize the security of their account.</span></p><br>
                <p><strong>Changes to the Sites</strong></p><br>
                <p><span>Sera Labs, Inc.® may, in its sole discretion, terminate, change, modify, suspend, make improvements to, or discontinue any aspect of the Sites or any products available through or outside of the Sites, temporarily or permanently, including the availability of any features of the Sites or access to any parts of the Sites, at any time without notice to you, and you agree that Sera Labs, Inc.® shall not be liable therefor.</span></p><br>
                <p><strong>Linked Sites</strong></p><br>
                <p><span>Sera Labs, Inc.® makes no claim or representation regarding, and accepts no responsibility for, the quality, content, nature, or reliability of sites accessible by hyperlink from the Sites, or sites linking to these Sites. The linked sites are not under the control of Sera Labs, Inc.®, and Sera Labs, Inc.® is not responsible for the content of any linked site or any link contained in a linked site, or any review, changes, or updates to such sites. The inclusion of any link does not imply affiliation, endorsement, or adoption by Sera Labs, Inc.® of the site or any information contained therein. When leaving the Sites, you should be aware that Sera Labs, Inc.® Terms and Conditions and policies no longer govern, and therefore you should review the applicable terms and policies, including privacy and data-gathering practices, of that site.</span></p><br>
                <p><strong>Copyright and Trademarks</strong></p><br>
                <p><span>All the Sites’ materials, including, without limitation, Sera Labs, Inc.® and all Sera Labs, Inc.® product logos, design, text, graphics, software, other files, and the selection and arrangement thereof (the “Content”) are Copyright © 2015, Sera Labs, Inc.®. ALL RIGHTS RESERVED. Unless expressly stated otherwise, Sera Labs, Inc.® or its suppliers or licensors own and retain other proprietary rights in all products available through the Sites. Except as stated herein, none of the Content may be copied, modified, reproduced, distributed, republished, downloaded, performed, displayed, posted, transmitted, sold, or made into derivative works in any form or by any means, including, but not limited to, electronic, mechanical, photocopying, recording, or otherwise, without the prior written permission of Sera Labs, Inc.® or the respective copyright owner. You may not, without the express written permission of Sera Labs, Inc.® or the respective copyright owner, (a) copy, publish, or post any materials on any computer network or broadcast or publications media; (b) modify the materials; or (c) remove or alter any copyright or other proprietary notices contained in the materials. You also may not (a) sell, resell, or make commercial use of the Sites, its content, or services or products obtained through the Sites; (b) collect and use of any product listings or descriptions; (c) make derivative uses of the Sites or its Content; or (d) use of any data mining, robots, or similar data gathering and extraction methods. You are not conveyed any right or license by implication, estoppel, or otherwise in or under any patent, trademark, copyright, or other proprietary right of Sera Labs, Inc.® or any third party.</span></p><br>
                <p><span><strong>Trademarks:</strong>&nbsp;Together with other logos and product names described on the Sites, the following is a trademark or registered trademark of Sera Labs, Inc.®, in the United States and other countries: Sera Labs, Inc.®. This trademark may not be copied, imitated, or used, in whole or in part, without the prior written permission of Sera Labs, Inc.® or the rights holder. In addition, all page headers, custom graphics, button icons, and scripts are service marks, trademarks, and/or trade dress of Sera Labs, Inc.®, and may not be copied, imitated, or used, in whole or in part, without the prior written permission of Sera Labs, Inc.®. Other names and brands may be claimed as the property of others.</span></p><br>
                <p><strong>Copyright Policy and Copyright Agent</strong></p><br>
                <p><span>It is Sera Labs, Inc.® policy to respect the copyright and intellectual property rights of others. Sera Labs, Inc.® may remove content that appears to infringe the copyright or other intellectual property rights, including moral rights, of others. In addition, Sera Labs, Inc.® may terminate access by users who appear to infringe the copyright or other intellectual property rights of others. Further, Sera Labs, Inc.® complies with the Digital Millennium Copyright Act. If you believe that Sera Labs, Inc.® or any user of our Sites has infringed your copyright in any material way, please notify Sera Labs, Inc.®, and provide the following:</span></p><br>
                <p><span>an identification of the intellectual property right claimed to have been infringed;</span></p><br>
                <p><span>an identification of the material that you claim is infringing so that we may locate it on the Sites; your address, telephone number, and email address;</span></p><br>
                <p><span>a statement by you that you have a good faith belief that the disputed use is not authorized by the owner, their licensee, and agent of either of the foregoing, or the law; and a statement by you that the above information in your notice is accurate, made under penalty of perjury, and that you are authorized to act on behalf of the owner of the intellectual property interest involved.</span></p><br>
                <p><span>Please direct inquiries regarding intellectual property infringement issues by email to&nbsp;<a href="https://help.seralabshealth.com/">help.seralabshealth.com</a>, or by mail to:</span></p><br>
                <p><span>Sera Labs, Inc®</span></p><br>
                <p><span>PO Box 55725</span></p><br>
                <p><span>Sherman Oaks, CA 91413</span></p><br>
                <p><span>Attn.: Chief Legal Officer</span></p><br>
                <p><strong>Indemnification</strong></p><br>
                <p><span>You agree to indemnify and hold harmless Sera Labs, Inc.®, its parents, subsidiaries, shareholders, officers, directors, employees, agents, and suppliers from any claim, action, demand, loss, or damages (including attorneys’ fees) made or incurred by any third party arising out of or relating to your use of the Site, your violation of these Terms and Conditions, or your violation of any rights of a third party.</span></p><br>
                <p><strong>Product Information</strong></p><br>
                <p><span>For questions about the products or services on this Site, please use the Customer Service email links found on each product page or section. For questions about orders placed through the Sites or otherwise, please use the Customer Service link in the email receipt you receive or by visiting the online Customer Service Center.</span></p><br>
                <p><strong>Our Guarantee</strong></p><br>
                <p><span>Most of our products carry a specific money back guarantee, return or exchange policy starting from the date that the product is ordered. You may check with customer service for more information.</span></p><br>
                <p><span>To return or exchange a product, please call our Customer Service at 1-800-625-4211 or&nbsp;<a href="https://help.seralabshealth.com/">help.seralabshealth.com</a>&nbsp;or for a Return Authorization Number and return the product within the required time period specific to your product. Products that come with a money-back guarantee will receive a refund of the purchase price, less any applicable shipping and handling and restocking fee/fees. We will not be responsible for any loss or damage to returned products that occur in transit. If returned products are lost or damaged in transit, we reserve the right to charge you for, or not refund any amounts attributable to, such products or loss or damage. Should you experience any difficulty or delay in returning a product and securing the proper refund, please visit our online Customer Service Center.</span></p><br>
                <p><strong>Product and Service Descriptions</strong></p><br>
                <p><span>We have taken reasonable precautions to try to ensure that all product descriptions, prices and other information shown on the Sites are correct and fairly described. However, when ordering products or services through the Sites, please note that:</span></p><br>
                <p><span>Sera Labs, Inc.® reserves the right not to accept any orders if there is a material error in the description of the product or service, or if the price advertised is incorrect;</span></p><br>
                <p><span>all prices are displayed in United States Dollars unless expressly indicated otherwise; packaging may vary from that shown on the Sites;</span></p><br>
                <p><span>any weights, dimensions, and capacities shown on the Sites are approximate only; and all items are subject to availability and we will inform you as soon as reasonably possible if the product(s) or service(s) you have ordered is not available and whether we may offer you an alternative product(s) or service(s) of equal or higher quality and value.</span></p><br>
                <p><span>Please also note that the terms of any products offered by Sera Labs, Inc.® and/or purchased by you, such as pricing, specifications, delivery times, and/or package contents are subject to change by Sera Labs, Inc.® by providing you advanced notice, including by posting notice of the change on our Sites, sending you an email to the address you provided at purchase. Sera Labs, Inc.® will not incur any obligation as a result of such change. As a valued customer, you are always free to cancel future orders at any time by calling our friendly Customer Service. By continuing to accept products after we have notified you of a change to any terms, you will be deemed to have accepted the change.</span></p><br>
                <p><strong>Order and Payment Information</strong></p><br>
                <p><span>If you use the Sites or other means to purchase a product, payment must be received by Sera Labs, Inc.® prior to Sera Labs, Inc.® acceptance of an order, unless otherwise agreed by Sera Labs, Inc.®. All Sera Labs, Inc.® products are subject to sales tax which will be applied to your order total. Sera Labs, Inc.® may need to verify information you provide before Sera Labs, Inc.® accepts an order, and may cancel or limit an order any time after it has been placed. If payment has already been made and your order is cancelled or limited, Sera Labs, Inc.® will refund any payment you made for the product that will not be shipped due to cancellation or limitation of an order in the same tender as the original purchase. Sera Labs, Inc.® expressly conditions its acceptance of your order on your agreement to these Terms and Conditions.</span></p><br>
                <p><span>In ordering products through the Sites or otherwise, you agree to provide only true, accurate, current, and complete information. You hereby certify that any email account you provide to Sera Labs, Inc.® is registered to you. Sera Labs, Inc.® shall have the right to bar your access to and use of the Sites or its other products or services if it has reasonable grounds to believe that you have provided untrue, inaccurate, not current, or incomplete information to Sera Labs, Inc.®, or for any other reason it, in its sole discretion, deems appropriate. You agree that if you are ordering or purchasing products on behalf of a company, that you have sufficient authority to bind that company to the Terms and Conditions. You agree that your placement of an electronic order on the Sites is sufficient to satisfy any applicable Statute of Frauds, and no further writing is required.</span></p><br>
                <p><span>Please choose the product that’s right for you. As part of your purchase you may be enrolled in our auto-delivery program, which allows you to cancel, reschedule or customize future shipments at any time with no minimum purchase required. Price and offer details for your selection are in the order summary on the checkout page, and a reminder email will be sent to you prior to any charge. We know you’re going to love your purchase, but if you’re unsatisfied for any reason all, unopened/unused, purchases are covered by our&nbsp;<strong>30-Day Money Back Guarantee</strong>, less restocking fee/fees.</span></p><br>
                <p><span>Sera Labs, Inc.® may reject orders where the stated delivery address is outside the United States, the United Kingdom and Canada. If stated, Sera Labs, Inc.® will add applicable shipping and handling fees.</span></p><br>
                <p><span>Sera Labs, Inc.® descriptions of, or references to, products not owned by Sera Labs, Inc.® on and outside of the Sites do not imply endorsement of that product, or constitute a warranty, by Sera Labs, Inc.®.</span></p><br>
                <p><strong>International Orders</strong></p><br>
                <p><span>Sera Labs, Inc.® does not directly sell certain Sera Labs, Inc.® products in any jurisdiction other than the United States of America as these products may not be approved for sale in other jurisdictions.</span></p><br>
                <p><strong>Shipping</strong></p><br>
                <p><span>Unless otherwise noted, Sera Labs, Inc.® will use commercially reasonable efforts to ship products within a reasonable time after receipt of your properly completed order. Although Sera Labs, Inc.® may provide delivery or shipment timeframes or dates, you understand that those are Sera Labs, Inc.® good-faith estimates and may be subject to change. You further understand that product availability may be limited and particular products may not be available for immediate delivery, in which case the products will be delivered when they become available. Sera Labs, Inc.® shall not be liable for any loss, damage, cost, or expense related to any delay in shipment or delivery.</span></p><br>
                <p><span>The delivery time for shipments within the United States or for shipments outside the United States, including to U.S. territories, Alaska and Hawaii, may take up to 7-21 days, Sera Labs,Inc.® does not ship to P.O. Boxes. Shipping and processing fees are non-refundable.</span></p><br>
                <p><strong>Automatic Renewal</strong></p><br>
                <p><span>We reserve the right to refuse or discontinue the supply of the Product to any user at any time at our sole discretion.</span></p><br>
                <p><strong>Warranties</strong></p><br>
                <p><span>CERTAIN WARRANTIES WITH RESPECT TO PARTICULAR PRODUCTS FOR SALE ON OR OUTSIDE THE SITES MAY BE APPLICABLE THROUGH MANUFACTURERS’ WARRANTIES, THOUGH NOT THROUGH SERA LABS, INC.®. SEE THE WARRANTIES INCLUDED IN THE DOCUMENTATION ALONG WITH THE PRODUCTS FOR FURTHER DETAILS REGARDING WARRANTIES PROVIDED BY MANUFACTURERS OF PRODUCTS AVAILABLE THROUGH OR OUTSIDE THE SITES.</span></p><br>
                <p><strong>Disclaimer of Warranties</strong></p><br>
                <p><span>YOU EXPRESSLY AGREE THAT USE OF THE SITES AND OTHER PRODUCTS AND SERVICES OF SERA LABS, INC® IS AT YOUR SOLE RISK. YOU UNDERSTAND AND AGREE THAT THE SITES AND THE INFORMATION, SERVICES, PRODUCTS, AND MATERIALS AVAILABLE THROUGH IT AND OTHERWISE ARE PROVIDED ON AN “AS-IS” AND “AS-AVAILABLE” BASIS. YOU ACKNOWLEDGE THAT SERA LABS, INC® DOES NOT CONTROL IN ANY RESPECT ANY ADVERTISEMENTS, PRODUCT DESCRIPTIONS, PRODUCTS, OR CONTENT OFFERED BY THIRD PARTIES ON OR THROUGH THE SITES, INCLUDING, BUT NOT LIMITED TO, INFORMATION OR PRODUCTS PROVIDED BY LICENSE TO SERA LABS, INC.® FROM THIRD PARTIES. EXCEPT AS OTHERWISE AGREED IN WRITING, SERA LABS, INC® AND ITS AFFILIATES ASSUME NO RESPONSIBILITY FOR AND MAKE NO WARRANTY OR REPRESENTATION AS TO THE ACCURACY, CURRENCY, COMPLETENESS, RELIABILITY, OR USEFULNESS OF CONTENT OR PRODUCTS (INCLUDING PRODUCT DESCRIPTIONS) DISTRIBUTED OR MADE AVAILABLE BY THIRD PARTIES THROUGH OR OUTSIDE OF THE SITES. NOR DOES SERA LABS, INC.® MAKE ANY WARRANTY AS TO THE RESULTS THAT MAY BE OBTAINED FROM USE OF THE SITES, ANY PRODUCTS OR SERVICES OFFERED OR SOLD THROUGH THE SITES, OR ITS CONTENT.</span></p><br>
                <p><span>ALTHOUGH SERA LABS, INC.® STRIVES TO PREVENT THE INTRODUCTION OF VIRUSES OR OTHER DESTRUCTIVE MATERIALS TO THE SITES, SERA LABS, INC.® DOES NOT WARRANT, GUARANTEE, OR MAKE ANY REPRESENTATIONS THAT THE SITES IS FREE OF DESTRUCTIVE MATERIALS. IN ADDITION, SERA LABS, INC.® DOES NOT WARRANT THAT ACCESS TO THE SITES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, OR THAT DEFECTS, IF ANY, WILL BE CORRECTED.</span></p><br>
                <p><span>SERA LABS, INC.® DISCLAIMS ANY WARRANTY OR REPRESENTATION THAT CONFIDENTIALITY OF INFORMATION TRANSMITTED THROUGH THE SITES WILL BE MAINTAINED. TO THE EXTENT ALLOWED BY LAW, SERA LABS, INC.® DISCLAIMS ALL WARRANTIES AND CONDITIONS NOT EXPLICITLY STATED HEREIN. SOME JURISDICTIONS DO NOT ALLOW THE LIMITATION OR EXCLUSION OF CERTAIN WARRANTIES OR CONDITIONS, SO SOME OF THE ABOVE EXCLUSIONS MAY NOT APPLY TO YOU.</span></p><br>
                <p><span>The terms of this section apply to the extent permitted by law and survive any termination of the Terms and Conditions.</span></p><br>
                <p><strong>Limitations on Liability</strong></p><br>
                <p><span>WE EXCLUDE ALL REPRESENTATIONS, WARRANTIES, CONDITIONS, AND TERMS (WHETHER EXPRESS OR IMPLIED BY STATUTE, COMMON LAW OR OTHERWISE) TO THE FULLEST EXTENT PERMITTED BY LAW.</span></p><br>
                <p><span>IN NO EVENT, INCLUDING, WITHOUT LIMITATION, NEGLIGENCE, SHALL SERA LABS, INC.® OR ITS AFFILIATES BE LIABLE FOR ANY DAMAGES, CLAIMS, OR LOSSES INCURRED (INCLUDING WITHOUT LIMITATION COMPENSATORY, INCIDENTAL, INDIRECT, SPECIAL, CONSEQUENTIAL, OR EXEMPLARY DAMAGES), HOWEVER CAUSED, AND UNDER ANY THEORY OF LIABILITY ARISING IN CONNECTION WITH: (I) THE SITES; (II) THE USE OR INABILITY TO USE THE SITES; (III) THE USE OF OR RELIANCE ON ANY CONTENT OR INFORMATION DISPLAYED IN OR ON THE SITES; (IV) THE PURCHASE OR USE OF ANY PRODUCTS THROUGH THE SITES OR OTHERWISE; (V) UNAUTHORIZED ACCESS TO OR ALTERATION OR LOSS OF YOUR TRANSMISSIONS OR DATA OR OTHER INFORMATION THAT IS SENT OR RECEIVED; (VI) ERRORS, SYSTEM DOWN TIME, NETWORK OR SYSTEM OUTAGES, OR FILE CORRUPTION OR SERVICE INTERRUPTIONS; OR (VII) OTHERWISE UNDER THIS AGREEMENT/TERMS AND CONDITIONS, WHETHER OR NOT REASONABLY FORESEEABLE, EVEN IF SERA LABS, INC.® OR ITS REPRESENTATIVES ARE ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, CLAIMS, OR LOSSES AND NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY. NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, SERA LABS, INC.® LIABILITY TO YOU FOR ANY CAUSE OF ACTION OR CLAIM WHATSOEVER, AND REGARDLESS OF THE FORM OF THE ACTION, WILL AT ALL TIMES BE LIMITED TO THE AMOUNT PAID, IF ANY, BY YOU IN THE LAST 90 DAYS TO SERA LABS, INC.® FOR ANY PRODUCTS SUPPLIED BY SERA LABS, INC.® THROUGH YOUR USE OF THE SITES OR OTHERWISE.</span></p><br>
                <p><span>SERA LABS, INC.® WILL NOT BE LIABLE IN ANY AMOUNT FOR FAILURE TO PERFORM ANY OBLIGATION UNDER THESE TERMS AND CONDITIONS IF SUCH FAILURE IS CAUSED BY THE OCCURRENCE OF ANY UNFORESEEN CONTINGENCY BEYOND ITS REASONABLE CONTROL, INCLUDING, WITHOUT LIMITATION, INTERNET OUTAGES, COMMUNICATIONS OUTAGES, FIRE, FLOOD, OR WAR. THESE EXCLUSIONS SHALL BE GOVERNED BY AND CONSTRUED IN ACCORDANCE WITH THE LAW OF THE UNITED STATES OF AMERICA. IF ANY PROVISION OR PART-PROVISION OF THESE TERMS AND CONDITIONS SHALL BE INVALID, UNLAWFUL, VOID, OR FOR ANY REASON UNENFORCEABLE IT SHALL BE DEEMED SEVERABLE AND SHALL NOT AFFECT THE VALIDITY AND ENFORCEABILITY OF THE REMAINING PROVISIONS OF THESE TERMS AND CONDITIONS.</span></p><br>
                <p><span>The terms of this section survive any termination of the Terms and Conditions.</span></p><br>
                <p><strong>International Users</strong></p><br>
                <p><span>The Sites are controlled, operated, and administered by Sera Labs, Inc.® from its offices within the United States of America. Sera Labs, Inc.® makes no representation that materials on the Sites are appropriate or available for use at other locations outside of the United States, and access to them from territories where the contents or products available through the Sites are illegal is prohibited. You may not use the Sites or export the content or products in violation of U.S. export laws and regulations. If you access the Sites from a location outside of the United States, you are responsible for compliance with all local laws.</span></p><br>
                <p><strong>Termination</strong></p><br>
                <p><span>Notwithstanding any of these Terms and Conditions, Sera Labs, Inc.® reserves the right, without notice and in its sole discretion, for any reason or no reason, to terminate your ability to use the Sites and to block or prevent future access to and use of the Sites. You agree that Sera labs, Inc.® shall not be liable for any termination of your use of or access to the Sites.</span></p><br>
                <p><strong>Third-party rights</strong></p><br>
                <p><span>Only you and Sera Labs, Inc.® shall be entitled to enforce these Terms and Conditions. No third party shall be entitled to enforce any of these Terms and Conditions.</span></p><br>
                <p><strong>Severability</strong></p><br>
                <p><span>If any provision of these Terms and Conditions, or part thereof, shall be deemed invalid, unlawful, void, or for any reason unenforceable by a court of competent jurisdiction, then that provision, or part thereof, shall be deemed severable from the rest of these Terms and Conditions and shall not affect the validity and enforceability of any remaining provisions or part thereof.</span></p><br>
                <p><span>The terms of this section survive any termination of the Terms and Conditions.</span></p><br>
                <p><strong>Language</strong></p><br>
                <p><span>It is the express intent of the parties that the Terms and Conditions and all related documents have been drawn up in English.</span></p><br>
                <p><span>DISPUTES, BINDING INDIVIDUAL ARBITRATION, AND WAIVER OF CLASS ACTIONS AND CLASS ARBITRATIONS.</span></p><br>
                <p><strong>Disputes</strong></p><br>
                <p><span>The terms of this Section shall apply to all Disputes between you and Sera Labs, Inc.®. For the purposes of this Section, “Dispute” shall mean any dispute, claim, or action between you and Sera Labs, Inc.® arising under or relating to the Products, the Sites, this Agreement, or any other transaction involving you and Sera Labs, Inc.®, whether in contract, warranty, misrepresentation, fraud, tort, intentional tort, statute, regulation, ordinance, or any other legal or equitable basis, and shall be interpreted to be given the broadest meaning allowable under law. YOU AND SERA LABS, INC.® AGREE THAT “DISPUTE” AS DEFINED IN THIS AGREEMENT SHALL NOT INCLUDE ANY CLAIM OR CAUSE OF ACTION BY YOU OR SERA LABS, INC.® FOR (A) TRADE SECRET MISAPPROPRIATION, (B) PATENT INFRINGEMENT, (C) COPYRIGHT INFRINGEMENT OR MISUSE, AND (D) TRADEMARK INFRINGEMENT OR DILUTION. Moreover, notwithstanding anything else in this Agreement, you agree that a court, not the arbitrator, may decide if a claim falls within one of these four exceptions.</span></p><br>
                <p><strong>Binding Arbitration</strong></p><br>
                <p><span>You and Sera Labs, Inc.® further agree: (a) to arbitrate all Disputes between the parties pursuant to the provisions in this Agreement; (b) this Agreement memorializes a transaction in interstate commerce; (c) the Federal Arbitration Act (9 U.S.C. §1, et seq.) governs the interpretation and enforcement of this Section; and (d) this Section shall survive termination of this Agreement. ARBITRATION MEANS THAT YOU WAIVE YOUR RIGHT TO A JUDGE OR JURY IN A COURT PROCEEDING AND YOUR GROUNDS FOR APPEAL ARE LIMITED. The arbitrator may award you the same damages as a court sitting in proper jurisdiction could, and may award declaratory or injunctive relief only in favor of the individual party seeking relief and only to the extent necessary to provide relief warranted by that party’s individual claim. In addition, in some instances, the costs of arbitration could exceed the costs of litigation and the right to discovery may be more limited in arbitration than in court. The decision of the arbitrator shall be final and enforceable by any court with jurisdiction over the parties. Small Claims Court. Notwithstanding the foregoing, you may bring an individual action in the small claims court of your state or municipality if the action is within that court’s jurisdiction and is pending only in that court.</span></p><br>
                <p><strong>Dispute Notice</strong></p><br>
                <p><span>In the event of a Dispute, you or Sera Labs, Inc.® must first send to the other party a notice of the Dispute that shall include a written statement that sets forth the name, address and contact information of the party giving it, the facts giving rise to the Dispute, and the relief requested (the “Dispute Notice”). The Dispute Notice to Sera Labs, Inc.® must be addressed to: Sera Labs, Inc.®, PO Box 55725, Sherman Oaks, CA, 91413, Attn.: Chief Legal Officer (the “Sera Labs, Inc.® Notice Address”). The Dispute Notice to you will be sent by certified mail to the most recent address we have on file or otherwise in our records for you. If Sera Labs, Inc.® and you do not reach an agreement to resolve the Dispute within sixty (60) days after the Dispute Notice is received, you or Sera Labs, Inc.® may commence an arbitration proceeding pursuant to this Section. Following submission and receipt of the Dispute Notice, each of us agrees to act in good faith to seek to resolve the Dispute before commencing arbitration.</span></p><br>
                <p><span>WAIVER OF CLASS ACTIONS AND CLASS ARBITRATIONS. YOU AND SERA LABS, INC.® AGREE THAT EACH PARTY MAY BRING DISPUTES AGAINST THE OTHER PARTY ONLY IN AN INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR REPRESENTATIVE PROCEEDING, INCLUDING WITHOUT LIMITATION FEDERAL OR STATE CLASS ACTIONS, OR CLASS ARBITRATIONS. ACCORDINGLY, UNDER THE ARBITRATION PROCEDURES OUTLINED IN THIS SECTION, AN ARBITRATOR SHALL NOT COMBINE OR CONSOLIDATE MORE THAN ONE PARTY’S CLAIMS WITHOUT THE WRITTEN CONSENT OF ALL AFFECTED PARTIES TO AN ARBITRATION PROCEEDING.</span></p><br>
                <p><strong>Arbitration Procedure</strong></p><br>
                <p><span>If a party elects to commence arbitration, the arbitration shall be governed by the rules of JAMS that are in effect at the time the arbitration is initiated (the “JAMS Rules”), available at https://www.jamsadr.com or by calling 1-800-352-5267, and under the rules set forth in this Agreement, except that JAMS may not administer any multiple claimant or class arbitration, as the parties agree that the arbitration shall be limited to the resolution only of individual claims. If there is a conflict between the JAMS Rules and the rules set forth in this Agreement, the rules set forth in this Agreement shall govern. You may, in arbitration, seek any and all remedies otherwise available to you pursuant to federal, state, or local laws. All Disputes shall be resolved by a single neutral arbitrator, and both parties shall have a reasonable opportunity to participate in the selection of the arbitrator. The arbitrator is bound by the terms of this Agreement. The arbitrator, and not any federal, state or local court or agency, shall have exclusive authority to resolve all disputes arising out of or relating to the interpretation, applicability, enforceability or formation of this Agreement, including, but not limited to, any claim that all or any part of this Agreement is void or voidable. Notwithstanding this broad delegation of authority to the arbitrator, a court may determine the limited question of whether a claim or cause of action is for (a) trade secret misappropriation, (b) patent infringement, (c) copyright infringement or misuse, or (d) trademark infringement or dilution, which are excluded from the definition of “Disputes” as stated above. The arbitrator shall be empowered to grant whatever relief would be available in a court under law or in equity. The arbitrator’s award shall be binding on the parties and may be entered as a judgment in any court of competent jurisdiction. You may choose to engage in arbitration hearings by telephone. Arbitration hearings not conducted by telephone shall take place in a location reasonably accessible from your primary residence, or in Los Angeles County, California, at your option.</span></p><br>
                <p><span>(a) Initiation of Arbitration Proceeding. If either you or Sera Labs, Inc.® decide to arbitrate a Dispute, we agree to the following procedure: (i) Write a Demand for Arbitration. The demand must include a description of the Dispute and the amount of damages sought to be recovered. You can find a copy of a Demand for Arbitration at https://www.jamsadr.com (“Demand for Arbitration”).</span></p><br>
                <p><span>(ii) Send three copies of the Demand for Arbitration, plus the appropriate filing fee, to:</span></p><br>
                <p><span>JAMS</span></p><br>
                <p><span>707 Wilshire Blvd</span></p><br>
                <p><span>46th Floor</span></p><br>
                <p><span>Los Angeles, CA 90017, U.S.A.</span></p><br>
                <p><span>(iii) Send one copy of the Demand for Arbitration to the other party at the same address as the Dispute Notice, or as otherwise agreed to by the parties. (b) Hearing Format. In all hearing formats, the arbitrator shall issue a written decision that explains the essential findings and conclusions on which an award, if any, is based. During the arbitration, the amount of any settlement offer made by Sera Labs, Inc.® or you shall not be disclosed to the arbitrator until after the arbitrator determines the amount, if any, to which you or Sera Labs, Inc.® is entitled. The discovery or exchange of non-privileged information relevant to the Dispute may be allowed during the arbitration.</span></p><br>
                <p><span>(c) Arbitration Fees. Sera Labs, Inc.® shall pay, or (if applicable) reimburse you for, all JAMS filing, administration, and arbitrator fees for any arbitration commenced (by you or Sera Labs, Inc.®) pursuant to provisions of this Agreement.</span></p><br>
                <p><span>(d) Opt-out. You may elect to opt-out (exclude yourself) from the final, binding individual arbitration procedure and waiver of class and representative proceedings specified in this Agreement by sending a written letter to the Sera Labs, Inc.® Notice Address within thirty (30) days of your assent to this Agreement (including the purchase of any Product or the use of the Sites) that specifies (i) your name, (ii) your mailing address, and (iii) your request to be excluded from the final, binding individual arbitration procedure and waiver of class and representative proceedings specified in this Section. In the event that you opt-out consistent with the procedure set forth above, all other terms shall continue to apply, including the requirement to provide notice prior to arbitration. Amendments to this Section. Notwithstanding any provision in this Agreement to the contrary, you and Sera Labs, Inc.® agree that if Sera Labs, Inc.® makes any future amendments to the dispute resolution procedure and class action waiver provisions (other than a change to Sera Labs, Inc.® address) in this Agreement, Sera Labs® will notify you and you will have thirty (30) days from the date of notice to affirmatively opt-out of any such amendments. If you affirmatively opt-out of any future amendments, you are agreeing that you will arbitrate any Dispute between us in accordance with the language of this Section as stated in this current Agreement, without any of the proposed amendments governing. If you do not affirmatively opt-out of any future amendments, you will be deemed to have consented to any such future amendments.</span></p><br>
                <p><span>Severability. If any provision in this Section is found to be unenforceable, that provision shall be severed with the remainder of this Agreement remaining in full force and effect. The foregoing shall not apply to the prohibition against class or representative actions; if the prohibition against class or representative actions is found to be unenforceable, this entire Section shall be null and void. The terms of this Section shall otherwise survive any termination of the Terms and Conditions.</span></p><br>
                <p><strong>Exclusive Venue for Other Controversies</strong></p><br>
                <p><span>Sera Labs, Inc.® and you agree that any controversy excluded from the dispute resolution procedure and class action waiver provisions in this Agreement (other than an individual action filed in small claims court) shall be filed only in the Superior Court of Los Angeles County, California, or the United States District Court for the Central District of California, and each party hereby irrevocably and unconditionally consent and submit to the exclusive jurisdiction of such courts for any such controversy.</span></p><br>
                <p><strong>General</strong></p><br>
                <p><span>The Terms and Conditions constitute the entire agreement between Sera Labs, Inc.® and you with respect to your use of the Sites, your purchase of products and services through the Sites, and as applicable any products or services of Sera Labs, Inc.®. Any cause of action you may have with respect to the Sites or Sera Labs, Inc.® products or services must be commenced within one (1) year after the claim or cause of action arises, notwithstanding any statutes of limitation to the contrary. The section titles used in the Terms and Conditions are purely for convenience and carry with them no legal or contractual effect. Nothing in these Terms and Conditions will be construed as creating a joint venture, partnership, employment, or agency relationship between you and Sera Labs, Inc.®, and you do not have any authority to create any obligation or make any representation on Sera Labs, Inc.® behalf. You may not assign or transfer any rights or obligations of these Terms and Conditions, by operation of law or otherwise, without Sera Labs, Inc.® written consent. Subject to the foregoing, these Terms and Conditions will be binding on, inure to the benefit of, and be enforceable against you and Sera Labs, Inc.® and their respective successors and assigns. The terms of this section survive any termination of the Terms and Conditions.</span></p><br>
                <p><strong>Other Important Terms</strong></p><br>
                <p><span>These Terms and Conditions supersede any other terms and conditions previously published by us and any other representations or statements made by us to you, whether oral, written, or otherwise. We may assign, transfer, or subcontract any of our rights or obligations under these Terms and Conditions to any third party at our discretion. No delay by us in exercising any right or remedy under these Terms and Conditions shall operate as waiver of that right or remedy or shall affect our ability to subsequently exercise that right or remedy. Any waiver must be agreed by us in writing.</span></p>
            `
            break;
        case "privacy":
            modalTitle = "Privacy Policy"
            modalContent =  `
                Effective Date:  March 26, 2019
                <br><br>
                Welcome! You have arrived at a web site that is provided by Sera Labs, Inc.® (“Sera Labs, Inc.®” or “we,” “our” or “us”). This “Privacy Policy” governs your use of website (including, without limitation, both mobile and online versions of our site and our shopping cart), and also applies to your use of all features, applications, content, downloads and other services that we make available through the site and/or that post a link to this Privacy Policy (collectively, referred to herein as the “Site”), regardless of how you access or use the Site, whether via personal computers, mobile devices or otherwise. This Privacy Policy is also in effect in regard to any offline communications with Sera Labs, Inc.® involving the purchase of our products and services. By using Site, or by sharing any information with Sera Labs, Inc.® when making offline purchases of its products and services, you signify that you have read, understand and agree to be bound by this Privacy Policy. To the extent we provide you notice on our Site of different or additional privacy policies or practices (e.g., at the point of our collection), those additional terms shall govern such data collection and use.  California residents have certain privacy rights detailed in the Section below. Your California Privacy Rights
                <br><br>
                In addition, please review the Site’s Terms and Conditions [www.seralabshealth.com], which governs your use of the Site. By using our Site, you consent to our Privacy Policy and Terms and Conditions and our collection, use and sharing of your information and data, and other activities, as described below. It is important that you read and understand the entire Privacy Policy before using the Site. However, this table of contents highlights key issues and points and you can click on the headings and the “More” links to be taken to the full explanation.
                What Information Does the Site Collect?
                <br><br>
                1. Information You Provide to Us
                You may provide us with Personal Information (defined below) and Demographic Information (defined below) such as when you purchase a product or service from the Site or sign up to receive information from us on the Site. (see below)
                <br><br>
                2. Information We Collect and Store as You Access and Use the Site
                Certain information may be collected from you automatically when you access and use the Site. For example, we and third parties may use Tracking Technologies (defined below) to collect Usage Information (defined below) based on your Device Identifier (defined below) for a variety of purposes, which may include activities over time and across third party locations. (see below)
                <br><br>
                3. Information Third Parties Provide About You
                We may obtain information about you from third parties. (see below)
                <br><br>
                4. Interactions with Third-Party Services
                If you interact with third-party services, those services may send us information about you and you or we may send them information about you. (see below)
                <br><br>
                5. Information You Provide About a Third Party
                You may provide us information about others, such as when you send a friend a gift from the Site. (see below)
                <br><br>
                6. Do Not Track Disclosure
                We do not look for or respond to do not track signals, but you may have certain other options regarding tracking and/or targeting. (see below)
                <br><br>
                7. How Do We Use the Information Collected?
                We use your Personal Information, Demographic Information and Usage Information for a variety of purposes detailed in this Section. (see below)
                <br><br>
                8. How and When Do We Disclose Information to Third Parties?
                We may provide your information to third parties under various circumstances detailed in this Section. These may include:
                <br><br>
                9. When You Request Information From or Provide Information to Third Parties
                If you request information from third parties, request that we send information to third parties or interact with third party services, content or tools (including Facebook and other third party share functionality), we may share your information with such parties and/or they may collect your information directly. (see below)
                <br><br>
                10. Third Parties Providing Services on our Behalf
                If you request information from third parties, request that we send information to third parties or interact with third party services, content or tools (including Facebook and other third party share functionality), we may share your information with such parties and/or they may collect your information directly. (see below)
                <br><br>
                11. Administrative and Legal Reasons
                There are a variety of administrative and legal reasons for which we may share your information. (see below)
                <br><br>
                12. Affiliates and Business Transfer
                We may share your information with our affiliates or in the event of a sale, merger or similar transaction. (see below)
                <br><br>
                13. Ads and Information About You
                We and third parties may send you targeted ads based on your location, information and/or behavior. If you object, you can exercise choices some third parties may offer. (see below)
                <br><br>
                14. Do Third-Party Content, Links to Third-Party Sites and/or Third-Party Apps Appear on the Site?
                We may allow you to access third-party content on the Site, or to link to third-party applications and locations from the Site, but we are not responsible for your interaction with third-party content, apps, and locations. (see below)
                <br><br>
                15. How Do I Change My Information and Communications Preferences?
                You may change certain information and preferences. (see below)
                <br><br>
                16. What About Transfer of Information to the United States?
                Data may be transferred to the United States. (see below)
                <br><br>
                17. What Should Parents Know About Children?
                We do not intend to collect Personal Information from children. If you think we have, let us know. (see below)
                <br><br>
                18. What About Security?
                No data security is absolute, but we take reasonable steps to secure data appropriately. (see below)
                <br><br>
                19. What About Changes to the Privacy Policy?
                We may change this Privacy Policy as explained here.
                <br><br>
                20. Your California Privacy Rights
                California residents have certain privacy rights as detailed here.
                The Full Detailed Privacy Policy
                What Information Does the Site Collect?
                <br><br>
                1. Information You Provide to Us
                On the Site, we may ask you to provide certain categories of information such as: (1) personally identifiable information, which is information that identifies you personally, such as your first and last name, email address, home address, phone number, and credit card number (“Personal Information”); and (2) demographic information, such as information about your gender and age (“Demographic Information”). We may collect this information through various forms and in various places on the Site, including through “contact us” forms, if you request to receive information from us or when you otherwise interact with the Site. If we combine Demographic Information with the Personal Information we collect directly from you on the Site, we will treat the combined data as Personal Information under this Privacy Policy.
                <br><br>
                2. Information We Collect and Store As You Access and Use the Site
                In addition to any Personal Information or other information that you choose to submit to us via our Site, we and our third-party service providers may use a variety of technologies that automatically (or passively) collect and store certain information whenever you visit or interact with the Site (“Usage Information”). This Usage Information may be stored or accessed using a variety of technologies that may be downloaded to your personal computer, browser, laptop, tablet, mobile phone or other device (a “Device”) whenever you visit or interact with our Site.
                <br><br>
                Usage Information may be non-identifying or may be associated with you. Whenever we associate Usage Information with your Personal Information, we will treat it as Personal Information. This Usage Information may include: your IP address, UDID or other unique identifier (“Device Identifier”). A Device Identifier is a number that is automatically assigned to your Device used to access the Site, and our computers identify your Device by its Device Identifier;  your Device functionality (including browser, operating system, hardware, mobile network information); the URL that referred you to our Site; the areas within our Site that you visit and your activities there, including remembering you and your preferences; your Device location; your Device characteristics; and certain other Device data, including the time of day, among other information.
                <br><br>
                We may use various methods and technologies to collect and store Usage Information (“Tracking Technologies”). Tracking Technologies may set, change, alter or modify settings or configurations on your Device. A few of the Tracking Technologies include, without limitation, the following (and subsequent technology and methods later developed):
                <br><br>
                Cookies. A cookie is a data file placed on a Device when it is used to visit the Site. A Flash cookie (or locally shared object) is a data file placed on a Device via the Adobe Flash plug-in that may be built-in to or downloaded by you to your Device. HTML5 cookies can be programmed through HTML5 local storage. Unlike Flash cookies, HTML5 cookies do not require a plug-in. Regular cookies may generally be disabled or removed by tools that are available as part of most commercial browsers, and in some but not all instances can be blocked in the future by selecting certain settings. Each browser you use will need to be set separately and different browsers offer different functionality and options in this regard. Also, these tools may not be effective with regard to Flash cookies or HTML5 cookies. For information on disabling Flash cookies, go to Adobe’s web site www.adobe.com. Please be aware that if you disable or remove cookies, Flash cookies, or HTML5 cookies on your Device, some parts of our Site may not function properly, and that when you revisit our Site your ability to limit cookies is subject to your browser settings and limitations.
                <br><br>
                Web Beacons. Small graphic images or other web programming code called web beacons (also known as “1×1 GIFs” or “clear GIFs”) may be included in our Site’s pages and messages. Web beacons may be invisible to you, but any electronic image or other web programming code inserted into a page or e-mail can act as a web beacon. Web beacons or similar technologies may be used for a number of purposes, including, without limitation, to count visitors to the Site, to monitor how users navigate the Site, to count how many e-mails that were sent were actually opened or to count how many particular articles or links were actually viewed. Embedded Scripts. An embedded script is programming code that is designed to collect information about your interactions with the Site, such as the links you click on. The code is temporarily downloaded onto your Device from our web server or a third-party service provider, is active only while you are connected to the Site and is deactivated or deleted thereafter.  Browser Fingerprinting. Collection and analysis of information from your Device, such as, without limitation, your operating system, plug-ins, system fonts and other data, for purposes of identification.
                <br><br>
                ETag, or entity tag. A feature of the cache in browsers. It is an opaque identifier assigned by a web server to a specific version of a resource found at a URL. If the resource content at that URL ever changes, a new and different ETag is assigned. Used in this manner ETags are a form of Device Identifier. ETag tracking may generate unique tracking values even where the consumer blocks HTTP, Flash and/or HTML5 cookies.
                <br><br>
                Recognition Technologies. Technologies, including application of statistical probability to data sets, which attempt to recognize or make assumptions about users and devices (e.g., that a user of multiple devices is the same user).
                <br><br>
                We may use Tracking Technologies for a variety of purposes, including: 
                <br><br>
                Strictly Necessary. We may use cookies or other Tracking Technologies that we consider are strictly necessary to allow you to use and access our Site, including cookies required to prevent fraudulent activity, improve security or allow you to make use of Site functionality.
                <br><br>
                Performance Related. We may use cookies or other Tracking Technologies that are useful in order to assess the performance of the Site, including as part of our analytic practices or otherwise to improve the content, products or services offered through the Site.
                <br><br>
                Functionality Related. We may use cookies or other Tracking Technologies that are required to offer you enhanced functionality when accessing the Site, including identifying you when you visit our Site or keeping track of our specified preferences, including in terms of the presentation of content on our Site.
                <br><br>
                Targeting Related. We may use Tracking Technologies to deliver content relevant to your interests on our Site and third party sites based on how you interact with our content. This includes using Tracking Technologies to understand the usefulness to you of the content that have been delivered to you. There may be other Tracking Technologies now and later devised and used by us in connection with the Site. Further, third parties may use Tracking Technologies in connection with our Site, which may include the collection of information about your online activities over time and across third-party web sites or online services. We may not control those Tracking Technologies and we are not responsible for them. However, you consent to potentially encountering third-party Tracking Technologies in connection with use of our Site and accept that our statements under this Privacy Policy do not apply to the Tracking Technologies or practices of such third parties.
                <br><br>
                1. Information Third Parties Provide About You
                We may receive information about you from your friends and others that use the Site, such as when they submit your information to us about you. Additionally, we may, from time to time, supplement the information we collect directly from you on our Site with outside records from third parties for various purposes, including to enhance our ability to serve you, to tailor our content to you and to offer you opportunities that may be of interest to you. To the extent we combine information we receive from those sources with your Personal Information we collect on the Site, it will be treated as Personal Information and we will apply this Privacy Policy to such combined information, unless we have disclosed otherwise. In no other circumstances do our statements under this Privacy Policy apply to information we receive about you from third parties.
                <br><br>
                2. Interactions with Third Party Services
                The Site may include functionality that allows certain kinds of interactions between the Site and your account on a third-party web site, application or other service. The use of this functionality may involve the third-party operator providing certain information, including Personal Information, to us. For example, we may provide third-party sites’ interfaces or links on the Site to facilitate your sending a communication from the Site. For example, we may use third parties to facilitate emails, Tweets or Facebook postings. These third parties may retain any information used or provided in any such communications or other activities and these third parties’ practices are not subject to our Privacy Policy. We may not control or have access to your communications through these third parties. Further, when you use third-party sites or services, you are using their services and not our services and they, not we, are responsible for their practices. You should review the applicable third-party privacy policies before using such third-party tools on our Site.
                <br><br>
                3. Information You Provide About a Third Party
                You may send someone else a communication from the Site, such as sending an invitation to a friend or if you send a gift to another person. If so, the information you provide (names, email addresses, mobile number, etc.) is used to facilitate the communication and process the transaction and is not used by us for any other marketing purpose unless we obtain consent from that person or we explicitly say otherwise. Please be aware that when you use any send-to-a-friend functionality on our Site, your email address, mobile number, name or user name and message may be included in the communication sent to your addressee(s).
                <br><br>
                4. Do Not Track Disclosure
                Various third parties are developing or have developed signals or other mechanisms for the expression of consumer choice regarding the collection of information about an individual consumer’s online activities over time and across third-party web sites or online services (e.g., browser do not track signals). Currently, we do not monitor or take any action with respect to these signals or other mechanisms.
                <br><br>
                5. How Do We Use the Information Collected?
                We may use your Personal Information, Demographic Information or Usage Information for various purposes, including: to place an order made through the Site and fulfill your order request; to notify you of product recalls or providing other information concerning products you have purchased; to improve merchandise selections and the overall shopping experience at the Site; to process transactions or provide you with information such as to send you electronic newsletters or to provide you with special offers or promotional and marketing materials on our behalf, including to let you know about new products, services or upcoming events; to improve the Site, our marketing endeavors or our Site offerings; to enable you to participate in a variety of the Site’s features such as to enable you to participate in online surveys; to customize your experience on the Site or to serve you specific content or ads that are relevant to you; to provide customer support; to contact you with regard to your use of the Site and, in our discretion, changes to the Website and/or Site’s policies; to identify your product and Site preferences so that you can be informed of new or additional products, services and promotions; to improve the overall experience at the Site; and for internal business purposes; and for purposes disclosed at the time you provide your information or as otherwise set forth in this Privacy Policy.
                <br><br>
                6. How and When Do We Disclose Information to Third Parties?
                We may share non-Personal Information, such as aggregated user statistics, with third parties. Further, we may share your Device Identifiers with third parties along with data related to you and your activities. We share your Personal Information with merchants and other payment processing service providers so they can process the transactions initiated from your Service account. We do not share your Personal Information that we have collected directly from you on our Service with third parties for those third parties’ direct marketing purposes unless you have consented (either through an opt-in or opt-out opportunity) at the time you provide your Personal Information. In addition, we may share the information we have collected about you, including Personal Information, as disclosed at the time you provide your information and as described below or otherwise in this Privacy Policy. We may disclose your information as follows:
                <br><br>
                7. When You Request Information From or Provide Information to Third Parties.
                You may be presented with an option on our Site to receive certain information and/or marketing offers directly from third parties or to have us send certain information to third parties or give them access to it. If you choose to do so, your Personal Information and other information may be disclosed to such third parties and all information you disclose will be subject to the third-party privacy policies and practices of such third parties. In addition, third parties may store, collect or otherwise have access to your information when you interact with their Tracking Technologies, content, tools apps or ads on our Site or link to them from our Site. This may include using third party tools such as Facebook, Twitter, Pinterest or other third-party posting or content sharing tools and by so interacting you consent to such third party practices. It may also include ordering or purchasing products from third parties through us where we indicate that the third party rather than us is the seller. We are not responsible for the privacy policies and practices of such third parties and, therefore, you should review such third party privacy policies and practices of such third parties prior to requesting information from or otherwise interacting with them.
                <br><br>
                8. Third Parties Providing Services on our Behalf.
                We may use third-party vendors to perform certain services on behalf of us or the Site, such as: (i) to assist us in Site operations; (ii) to manage a database of customer information; (iii) hosting the Site; (iv) designing and/or operating the Site’s features; (v) tracking the Site’s activities and analytics; (vi) enabling us to send you special offers or perform other administrative services; and (vii) other services designed to assist us in maximizing our business potential. We may provide these vendors with access to user information, including Device Identifiers and Personal Information, to carry out the services they are performing for you or for us. Third-party analytics and other service providers may set and access their own Tracking Technologies on your Device and they may otherwise collect or have access to information about you, potentially including Personal Information, about you. We are not responsible for those third party technologies or activities arising out of them. However, some may offer you certain choices regarding their practices, and information we have been informed of regarding such choices is available in Section 4 below. We are not responsible for the effectiveness of or compliance with any third parties’ opt-out options.
                <br><br>
                9. Administrative and Legal Reasons.
                We may access, use, preserve, transfer and disclose your information (including Device Identifiers and Personal Information) to third parties: (i) to satisfy any applicable law, regulation, subpoenas, governmental requests or legal process if in our good faith opinion such is required or permitted by law; (ii) to protect and/or defend the Site’s Terms and Conditions or other policies applicable to the Site, including investigation of potential violations thereof; (iii) to protect the safety, rights, property or security of the Site or any third party; and/or (iv) to detect, prevent or otherwise address fraud, security or technical issues. Further, we may use IP address or other Device Identifiers, to identify users, and may do so in cooperation with third parties such as copyright owners, internet service providers, wireless service providers and/or law enforcement agencies, including disclosing such information to third parties, all in our discretion, subject to applicable law. Such disclosures may be carried out without notice to you.
                <br><br>
                10. Affiliates and Business Transfer.
                We may share your information, including your Device Identifiers and Personal Information, Demographic Information and Usage Information with our parent, subsidiaries and affiliates. We also reserve the right to disclose and transfer all such information: (i) to a subsequent owner, co-owner or operator of the Site or applicable database; or (ii) in connection with a merger, consolidation, restructuring, the sale of substantially all of our interests and/or assets or other corporate change, including, during the course of any due diligence process.
                <br><br>
                11. Ads and Information About You.
                Data about your activities online is being collected on our Site for use in providing advertising tailored to your individual interests based on your browsing of the Site and elsewhere on the Internet, sometimes referred to as “interest-based advertising” and “online behavioral advertising” (“Interest-based Advertising”). We may use third parties such as network advertisers and ad exchanges to serve advertisements across the Internet and may use third party analytics service providers to evaluate and provide us and/or third parties with information about the use of these ads on third party websites and viewing of ads and of our content. Third parties may offer you a choice as to whether or not to have your information collected for that purpose. This section of the privacy policy provides details and explains how to exercise that choice. You may see certain ads on our Site as well as on other third-party websites across the Internet because we participate in advertising networks administered by third parties. These networks track your online activities over time and across third party websites by collecting information through automated means, including through the use of the tracking technologies described elsewhere in this Privacy Policy, and they use this information to show you advertisements (including our ads) that are tailored to your individual interests. The information they collect includes information about your visits to our Site, such as the pages you have viewed. These third party tracking technologies may be set to, among other things: (a) help deliver advertisements to you that you might be interested in; (b) prevent you from seeing the same advertisements too many times; and (c) understand the usefulness to you of the advertisements that have been delivered to you. You acknowledge and agree that associated technology may access and use your device and may set or change settings on your device in connection with the associated operations. Note that any images (or any other parts of content) served by third parties in association with third-party ads or other content may act as web beacons, which enable third parties to carry out the previously described activities.
                <br><br>
                This collection and ad targeting takes place both on our Site and on third-party websites that participate in the ad network, such as websites that feature advertisements delivered by the ad network. This process also helps us track the effectiveness of our marketing efforts. We and third-party vendors, including Google, use first-party cookies (such as the Google Analytics cookie) and third-party cookies (such as a DoubleClick cookie) together to report how your ad impressions, other uses of ad services, and interactions with these ad impressions and ad services are related to visits to our Site. To learn more about how to opt-out of Google’s use of cookies, visit the Google’s Ads Settings. To learn more about how to opt out of DoubleClick’s use of cookies, visit the DoubleClick opt-out page.
                <br><br>
                Third-party tracking technologies are not controlled by us, even if they use our technology to help store or collect data. Statements regarding our practices do not apply to the methods for collecting information used by these third-party advertisers and others or the use of the information that such third parties collect. We do however work with third parties to make efforts to provide you with information on their practices and any available opportunity to exercise choice. The relevant third party’s terms of service, privacy policy, permissions, notices and choices should be reviewed regarding their collection, storage and sharing practices. We make no representations regarding the policies or practices of third-party advertisers or advertising networks or exchanges or related third parties. Further, while we may use a variety of companies to serve advertisements on the website, you may wish to visit https://www.networkadvertising.org/choices, which provides information regarding this practice by Network Advertising Initiative (“NAI”) members, and your choices regarding having this information used by these companies, including the “opt-out” procedures of NAI members. Opting out of one or more NAI members only means that those NAI members no longer will be allowed under their own rules to deliver targeted content and/or ads to you, which will affect this and other sites, but does not mean you will no longer receive any targeted content and/or ads. Also, if your browsers are configured to reject cookies when you visit this opt-out page, or you subsequently erase your cookies, use a different device or change web browsers, your NAI opt-out may not, or may no longer, be effective. Additional information is available on the NAI’s website accessible by the above link. You may also be able to opt-out of receiving third-party behavioral ads by visiting the Digital Advertising Alliance (“DAA”) website at https://www.aboutads.info/choices/. Similar limitations may apply to the DAA opt-out. We support the ad industry’s 2009 Self-regulatory Principles for Online Behavioral Advertising (https://www.iab.com/wp-content/uploads/2015/05/ven-principles-07-01-09.pdf) and expect that ad networks we directly engage to serve you Interest-based Advertising will do so as well, though we cannot guarantee their compliance. We are not responsible for effectiveness of, or compliance with, any third-parties’ opt-out options or programs or the accuracy of their statements regarding their programs.
                Do Third-Party Content, Links to Third-Party Sites and/or Third-Party Apps Appear on the Site?
                <br><br>
                The Site may contain content, links or apps that are supplied by a third party, and those third parties may collect Usage Information and your Device Identifier when pages from the Site are served to you for their own commercial purposes. In addition, when you are on the Site you may be directed to other sites and apps that are operated and controlled by third parties that we do not control. We are not responsible for the data collection and privacy practices employed by any of these third parties or their sites or apps and they may be tracking you across multiple online services and may be sharing the results of that tracking with us and/or others.
                <br><br>
                These third parties may have their own terms of service, privacy policies or other policies and ask you to agree to the same. For example, if you “click” on a link, the “click” may take you off the Site onto a different location. These other online services may associate their Tracking Technologies with you, independently collect information about you, including Personal Information, and may or may not have their own published privacy policies. We are not responsible for these third-party privacy policies or the practices of third-party owners. Be sure to review any available policies before submitting any personally identifiable information to a third-party application or otherwise interacting with it and exercise caution in connection with these applications. We also encourage you to note when you leave our Site and to review the third-party privacy policies of all third-party locations and exercise caution in connection with them.
                How Do I Change My Information and Communications Preferences?
                <br><br>
                You are responsible for maintaining the accuracy of the information you submit to us, such as your contact information provided as part of registration. The Site may allow you to review, correct or update Personal Information you have provided through the Site’s forms, and you may provide updates and changes by contacting us via email at help.seralabshealth.com or 1-800-625-4211. If so, we will make good faith efforts to make requested changes in our then active databases as soon as reasonably practicable (but we may retain prior information as business records). Please note that it is not always possible to completely remove or delete all of your information from our databases and that residual data may remain on backup media or for other reasons.
                <br><br>
                You may cancel or modify our email marketing communications you receive from us by following the instructions contained within our promotional emails or in some cases by logging into your Site account and changing your communication preferences. This will not affect subsequent subscriptions and if your opt-out is limited to certain types of emails the opt-out will be so limited. Subsequent or different subscriptions will be unaffected. Please note that we reserve the right to send you certain communications relating to your account or use of our Site, such as administrative and Site announcements and these transactional account messages may be unaffected if you choose to opt-out from receiving our marketing communications, via email, STOP SMS/Text, or contact via phone. If you have any questions about the Privacy Policy or practices described in it, you should contact us via email at help.seralabshealth.com or 1-800-625-4211.
                <br><br>
                1. What About Transfer of Information to the United States?
                Our Site is operated in the United States and intended for users located in the United States. If you are located outside of the United States, please be aware that information we collect, including Personal Information, will be transferred to, and processed, stored and used in the United States. The data protection laws in the United States may differ from those of the country in which you are located, and your Personal Information may be subject to access requests from governments, courts, or law enforcement in the United States according to laws of the United States. By using the Site or providing us with any information, you consent to the transfer to, and processing, usage, sharing and storage of your information, including Personal Information, in the United States as set forth in this Privacy Policy.
                <br><br>
                2. What Should Parents Know About Children?
                The Site is intended for a general audience and not directed to children less than 13 years of age. We do not intend to collect any personal information as defined by the U.S. Children’s Online Privacy Protection Act (“COPPA”) (“Children’s Personal Information”) in a manner that is not permitted by COPPA. If we obtain knowledge that we have collected Children’s Personal Information in a manner not permitted by COPPA, we will remove such data to the extent required by COPPA. If you are a parent or legal guardian of a child under the age of thirteen (13) and believe he or she has disclosed personal information to us, please contact us via email at help.seralabshealth.com or 1-800-625-4211. Any California residents under the age of eighteen (18) who have registered to use the Site, and who posted content or information on the Service, can request removal by contacting us, detailing where the content or information is posted and attesting that you posted it.  We will then make reasonable good faith efforts to remove the post from prospective public view or anonymize it so the minor cannot be individually identified to the extent required by applicable law. This removal process cannot ensure complete or comprehensive removal. For instance, third-parties may have republished or archived content by search engines and others that we do not control.
                <br><br>
                3. What About Security?
                We endeavor to incorporate commercially reasonable safeguards to help protect and secure your Personal Information. However, no data transmission over the Internet, mobile networks, wireless transmission or electronic storage of information can be guaranteed to be 100% secure. Please note that we cannot ensure the security of any information you transmit to us, and you use our Site and provide us with your information at your own risk.
                <br><br>
                4. What About Changes to the Privacy Policy?
                We reserve the right to change this Privacy Policy at any time without notice to you. Any changes will be effective immediately upon the posting of the revised Privacy Policy and your use of our Site indicates your consent to the privacy policy posted at the time of use. However, we will not use your previously collected Personal Information in a manner materially different than indicated at the time it was collected without your consent. To the extent any provision of this Privacy Policy is found by a competent tribunal to be invalid or unenforceable, such provision shall be severed to the extent necessary for the remainder to be valid and enforceable.
                <br><br>
                5. Your California Privacy Rights
                We provide California residents with the option to opt-in or opt-out to sharing of “personal information” as defined by California’s “Shine the Light” law with third parties, other than our affiliates, for such third parties own direct marketing purposes.  California residents may exercise that opt-out, and/or request information about our compliance with the Shine the Light law, and obtain disclosure of third parties we have shared information in accordance with the law for their direct marketing purposes absent your choice and the categories of information shared, by sending us an e-mail at help.seralabshealth.com or by sending a letter to us at:
                <br><br>
                The Sera Labs (Attention: Customer Service)
                <br><br>
                41 Canal Street
                <br><br>
                Lewiston, Maine 04240
                <br><br>
                Requests must include “California Privacy Rights Request” in the first line of the description and include your name, street address, city, state, and ZIP code.  Please note that we are only required to respond to one request per customer each year, and we are not required to respond to requests made by means other than through the provided e-mail address or mailing address.
            `
            break;
        case "contact":
            modalTitle = "Contact Us"
            modalContent = `<iframe style="width:100%;height:100%;" src="https://help.seralabshealth.com/session"></iframe>`
    }

        $('.modal-title').html(`
            <h1>${modalTitle}</h1>
        `);
        $('.modal-body').html(modalContent);
  })